# Generated by Django 4.2.27 on 2025-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Ações', 'Ações'), ('FIIs', 'FIIs'), ('ETFs', 'ETFs'), ('Futuros', 'Futuros'), ('Outros', 'Outros')], max_length=50)),
                ('asset_class', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=20)),
                ('liquid_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('buy_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sell_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
