# Generated by Django 5.2.2 on 2025-06-14 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada no Reforço'),
        ),
    ]
