# Generated by Django 5.2.4 on 2025-09-09 18:12

import django.db.models.deletion
import django.utils.timezone
import prograos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amostra', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('tipo_grao', models.CharField(choices=[('SOJA', 'Soja'), ('MILHO', 'Milho')], max_length=10)),
                ('peso_bruto', models.DecimalField(decimal_places=3, max_digits=10)),
                ('umidade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('impurezas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_util', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_criadas', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PesagemCaminhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=10)),
                ('data_tara', models.DateTimeField(blank=True, null=True, verbose_name='Data da Tara')),
                ('data_final', models.DateTimeField(blank=True, null=True, verbose_name='Data Final')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa Carreta/Placa')),
                ('placa_cavalo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa Veíc/Cavalo')),
                ('motorista', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Motorista')),
                ('transportadora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transportadora')),
                ('operador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador')),
                ('tara', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Peso da Tara (kg)')),
                ('peso_carregado', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso Carregado (kg)')),
                ('peso_liquido', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tipo_grao', models.CharField(choices=[('SOJA', 'Soja'), ('MILHO', 'Milho')], max_length=10)),
                ('quantidade_sacos', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('valor_custo_por_saco', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Custo por Saco (R$)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesagens_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotaCarregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_recebedor', models.CharField(max_length=255)),
                ('cpf_cnpj_recebedor', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_recebedor', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_recebedor', models.TextField(blank=True, null=True)),
                ('tipo_grao', models.CharField(choices=[('SOJA', 'Soja'), ('MILHO', 'Milho')], max_length=10)),
                ('quantidade_sacos', models.DecimalField(decimal_places=3, max_digits=10)),
                ('preco_por_saco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_criadas', to=settings.AUTH_USER_MODEL)),
                ('pesagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prograos.pesagemcaminhao')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pagamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total da Operação')),
                ('lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro da Operação')),
                ('nota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='prograos.notacarregamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pagamento', models.CharField(choices=[('PIX', 'Pix'), ('BOLETO', 'Boleto'), ('DINHEIRO', 'Dinheiro')], default='PIX', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to=prograos.models.comprovante_upload_path, verbose_name='Comprovante de Pagamento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registro_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='prograos.registrofinanceiro')),
            ],
        ),
    ]
