# Generated by Django 5.2.4 on 2026-01-08 13:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prograos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Certificado')),
                ('certificate_file', models.FileField(help_text='Upload do arquivo .pfx do certificado A1', upload_to='certificates/', verbose_name='Arquivo do Certificado (.pfx)')),
                ('password', models.CharField(help_text='Senha será criptografada no banco de dados', max_length=255, verbose_name='Senha do Certificado')),
                ('valid_from', models.DateField(verbose_name='Válido de')),
                ('valid_to', models.DateField(verbose_name='Válido até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitais',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmitterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('ie', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('im', models.CharField(blank=True, max_length=20, null=True, verbose_name='Inscrição Municipal')),
                ('regime_tributario', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Exc. Receita'), ('3', 'Regime Normal')], default='1', max_length=1, verbose_name='Regime Tributário')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('c_mun', models.CharField(max_length=7, verbose_name='Código IBGE Município')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('serie_nfe', models.IntegerField(default=1, verbose_name='Série NF-e')),
                ('numero_atual_nfe', models.IntegerField(default=1, verbose_name='Próximo Número NF-e')),
                ('ambiente', models.IntegerField(choices=[(2, 'Homologação'), (1, 'Produção')], default=2, verbose_name='Ambiente')),
                ('production_enabled', models.BooleanField(default=False, help_text='ATENÇÃO: Habilite apenas após validação do contador', verbose_name='Produção Habilitada')),
                ('accountant_validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validado pelo Contador em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Emitente',
                'verbose_name_plural': 'Configuração do Emitente',
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_type', models.CharField(choices=[('SOJA', 'Soja'), ('MILHO', 'Milho')], max_length=10, unique=True, verbose_name='Tipo de Grão')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição do Produto')),
                ('ncm', models.CharField(help_text='Ex: 12019000 para Soja, 10059000 para Milho', max_length=8, verbose_name='NCM')),
                ('cfop_inside_state', models.CharField(choices=[('5101', '5101 - Venda de produção do estabelecimento'), ('5102', '5102 - Venda de mercadoria adquirida'), ('6101', '6101 - Venda de produção - fora do estado'), ('6102', '6102 - Venda de mercadoria - fora do estado')], default='5101', max_length=4, verbose_name='CFOP - Dentro do Estado')),
                ('cfop_outside_state', models.CharField(choices=[('5101', '5101 - Venda de produção do estabelecimento'), ('5102', '5102 - Venda de mercadoria adquirida'), ('6101', '6101 - Venda de produção - fora do estado'), ('6102', '6102 - Venda de mercadoria - fora do estado')], default='6101', max_length=4, verbose_name='CFOP - Fora do Estado')),
                ('cst_csosn', models.CharField(default='101', help_text='Ex: 101 para Simples Nacional com crédito', max_length=3, verbose_name='CST/CSOSN')),
                ('icms_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota ICMS (%)')),
                ('pis_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota PIS (%)')),
                ('cofins_aliquota', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota COFINS (%)')),
                ('unit_com', models.CharField(default='KG', help_text='Ex: KG, TON, SC (saco)', max_length=10, verbose_name='Unidade Comercial')),
                ('accountant_validated', models.BooleanField(default=False, verbose_name='Validado pelo Contador')),
                ('notes', models.TextField(blank=True, help_text='Notas do contador sobre esta configuração', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil Tributário',
                'verbose_name_plural': 'Perfis Tributários',
            },
        ),
        migrations.AddField(
            model_name='pesagemcaminhao',
            name='frete_por_saco_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pesagemcaminhao',
            name='frete_total_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pesagemcaminhao',
            name='valor_frete_por_tonelada',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Frete (R$/Ton)'),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amostra',
            name='peso_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesagemcaminhao',
            name='peso_carregado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Carregado (kg)'),
        ),
        migrations.AlterField(
            model_name='pesagemcaminhao',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesagemcaminhao',
            name='tara',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso da Tara (kg)'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número Interno')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('customer_document', models.CharField(max_length=20, verbose_name='CPF/CNPJ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Emissão')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('READY', 'Pronto para Emissão'), ('ISSUED', 'Emitida'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('weighing_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prograos.pesagemcaminhao', verbose_name='Pesagem Vinculada')),
            ],
        ),
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(blank=True, max_length=44, null=True, verbose_name='Chave de Acesso')),
                ('series', models.IntegerField(default=1, verbose_name='Série')),
                ('number', models.IntegerField(verbose_name='Número NF-e')),
                ('xml', models.TextField(blank=True, null=True, verbose_name='XML Autorizado')),
                ('protocol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo de Autorização')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('AUTHORIZED', 'Autorizada'), ('DENIED', 'Denegada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('environment', models.CharField(choices=[('HOMOLOGATION', 'Homologação'), ('PRODUCTION', 'Produção')], default='HOMOLOGATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfe', to='prograos.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='NFeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CANCELAMENTO', 'Cancelamento'), ('CCE', 'Carta de Correção Eletrônica'), ('INUTILIZACAO', 'Inutilização')], max_length=20, verbose_name='Tipo de Evento')),
                ('description', models.TextField(verbose_name='Descrição/Justificativa')),
                ('xml_event', models.TextField(blank=True, null=True, verbose_name='XML do Evento')),
                ('protocol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SUCCESS', 'Sucesso'), ('ERROR', 'Erro')], default='PENDING', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='prograos.nfe', verbose_name='NF-e')),
            ],
            options={
                'verbose_name': 'Evento NF-e',
                'verbose_name_plural': 'Eventos NF-e',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NFeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Produto')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('cfop', models.CharField(max_length=4, verbose_name='CFOP')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Valor Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='prograos.nfe')),
            ],
        ),
    ]
